### ISSUE TITLE
partial write: unable to parse 'spaced item names with ('

### ISSUE THREAD

**Issue by darrynv** [LMacPhail/zabbix-history-influxdb#1]
First off. Thank you. 

Zabbix 3.4.14 

Getting these : 
{"error":"partial write: unable to parse 'Host\\ uptime\\ (in\\ sec),host_name=server1.com,host_groups=Discovered\\ hosts|Enterprise\\ Linux/Servers,applications= value=2834251.000000 1539627138427906142': missing tag value dropped=0"}
{"error":"unable to parse 'Host\\ uptime\\ (in\\ sec),host_name=server1.com,host_groups=Discovered\\ hosts|Enterprise\\ Linux/Servers,applications= value=2818935.000000 1539641899501574380': missing tag value\nunable to parse 'Host\\ uptime\\ (in\\ sec),host_name=server1.com,host_groups=Discovered\\ hosts|Enterprise\\ Linux/Servers,applications= value=2850365.000000 1539641900296451417': missing tag value"} {"error":"partial write: unable to parse 'Host\\ uptime\\ (in\\ sec),host_name=server1.com,host_groups=Discovered\\ hosts|Enterprise\\ Linux/Servers,applications= value=18147777.000000 1539641927380343756': missing tag value dropped=0"} {"error":"partial write: unable to parse 'Host\\ uptime\\ (in\\ sec),host_name=server1.com,host_groups=Discovered\\ hosts|Enterprise\\ Linux/Servers|Application\\ -\\ Consul\\ Vault,applications= value=2907978.000000 1539641967865403453': missing tag value dropped=0"}

I'm taking it that every item has to have a TAG value associated with it in order to be written to Influx?

**Comment by i-ky** [comment]
Hi! Can #2 be a solution?
