### ISSUE TITLE
Item name placeholders $1-$9 not correctly replaced when using MySQL

### ISSUE THREAD

**Issue by vasekch** [LMacPhail/zabbix-history-influxdb#13]
This is observed when using web checks.

Item key `web.test.rspcode[CURL mockapp - http,Homepage]`
Item name `Response code for step "$2" of scenario "$1".`

_Actual value in InfluxDB:_
`Response code for step "CURL mockapp - http,Homepage regexp" of scenario "CURL mockapp - http".`

_Expected value in InfluxDB:_
`Response code for step "Homepage regexp" of scenario "CURL mockapp - http".`

Bug is in the block of code after https://github.com/LMacPhail/zabbix-history-influxdb/blob/master/src/history_influxdb.c#L294

This does work as expected when using PostgreSQL.

**Comment by bbrendon** [comment]
The documentation says it doesn't support MySQL. Is that not the case?

**Comment by i-ky** [comment]
Check the [documentation](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring-index):
> <code>SUBSTRING_INDEX(_**str**_,_**delim**_,_**count**_)</code>
>
> Returns the substring from string _**str**_ before _**count**_ occurrences of the delimiter _**delim**_.

And also example:
```mysql
mysql> SELECT SUBSTRING_INDEX('www.mysql.com', '.', 2);
        -> 'www.mysql'
```

`substing_index()` will only produce correct replacement for `$1`.

[Internet](https://www.gyrocode.com/articles/how-to-split-and-search-in-comma-separated-values-in-mysql/) [suggests](https://www.got-it.ai/solutions/sqlquerychat/sql-help/data-manipulation/how-to-split-comma-separated-values-in-mysql-querychat/) suggests to "double wrap" string in `substring_index()` to emulate PostgreSQL's [`split_part()`](https://www.postgresql.org/docs/12/functions-string.html):
```mysql
mysql> SELECT SUBSTRING_INDEX(SUBSTRING_INDEX('www.mysql.com', '.', 2), '.', -1);
        -> 'mysql'
```

I'm going to file a PR shortly.

**Comment by i-ky** [comment]
@LMacPhail, are you still maintaining this project?

**Comment by i-ky** [comment]
@vasekch, have you tried #15?
