### ISSUE TITLE
Query result returned null

### ISSUE THREAD

**Issue by anton-xqz** [LMacPhail/zabbix-history-influxdb#3]
First of all, nice plugin and great job!
I got this issue in my setup:
   185:20190113:091424.276 [history_influxdb.so] query result returned null

I'm using zabbix 4.0.3, PostgreSQL 10.5 (AWS RDS), InfluxDB 1.7.2

After I get this error zabbix server shutting down.

**Comment by i-ky** [comment]
This error comes from [this place](https://github.com/LMacPhail/zabbix-history-influxdb/blob/968511bd01499ac8efaad9044c8ebd5ae6890014/src/history_influxdb.c#L271) in `itemid_to_influx_data()` function. Judging by its name, it should gather some information about the item given `itemid`. For performance reasons Zabbix does not have a foreign key constraint on `itemid` field in `history*` tables and Zabbix can actually write values of deleted items into history. I think `exit(EXIT_FAILURE);` is not the right thing to do in case query returns nothing.

@anton-xqz, could you please find [this](https://github.com/LMacPhail/zabbix-history-influxdb/blob/968511bd01499ac8efaad9044c8ebd5ae6890014/src/history_influxdb.c#L218-L264) query in the log of DB server, extract `itemid` from it and check if this item still exists in your setup to prove or reject my hypothesis?

**Comment by anton-xqz** [comment]
![image](https://user-images.githubusercontent.com/38725804/51084761-e985a200-1737-11e9-8539-562fb47ab857.png)
Unfortunately AWS RDS console limits me with display option. You can see uploaded image. This is the only  thing I can see about queries are running against DB.
I can suggest to make some changes to be able to locate the itemid. Make changes to code and do and output to log (INFO level) of relevant itemid. I will load it to zabbix and this way we can progress. What do you think?

**Comment by i-ky** [comment]
Hm, doesn't **Copy full SQL** button help?

I can do the changes to the code. Will you be able to compile from source yourself?

**Comment by anton-xqz** [comment]
Copy full SQL just copy the text you see...)))
I can to compile from source.

**Comment by anton-xqz** [comment]
This is my workaround in meanwhile:

> 	else {
> 		zabbix_log(LOG_LEVEL_ERR, "[%s] query result returned null", MODULE_NAME);
> 		return NULL;
> 	}

> 		influx_data = itemid_to_influx_data(itemid);
> 		if (NULL == influx_data) {
> 		    return;
> 		}

**Comment by i-ky** [comment]
Close enough! You can try this branch: https://github.com/i-ky/zabbix-history-influxdb/tree/missing-itemid

**Comment by anton-xqz** [comment]
Thanks, I will get a try.
BTW to be able to work with zabbix_server 4+ you should change it:
"from groups g " -> "from hstgrp g "

**Comment by i-ky** [comment]
That's true. Could you create a separate issue about it?

**Comment by anton-xqz** [comment]
206:20190113:145711.053 [history_influxdb.so] missing information for itemid 218778
   206:20190113:145711.063 [history_influxdb.so] missing information for itemid 218779
   206:20190113:145711.089 [history_influxdb.so] missing information for itemid 218777

This is the log output I get after your changes. Good.
Tomorrow I will check if these items still exist in the DB.

**Comment by anton-xqz** [comment]
Well... I don't find all itemids that I see in Zabbix server log from this module.
Another question: what is your module doing when this happening?
I think about other scenario that can happen: when new item arrives Zabbix for first time and not committed to DB yet. This way module will get nothing from DV query.

**Comment by i-ky** [comment]
> Another question: what is your module doing when this happening?

I must say that this is not my module. The fork I've pointed you to above skips values it can not find additional information for.

> when new item arrives Zabbix for first time and not committed to DB yet.

Zabbix creates items (and other entities) in DB first. This scenario cannot happen.

**Comment by i-ky** [comment]
Hey @anton-xqz, how is your testing going? Are there any issues with the fix, any improvements to be made? Or should I just create a PR?

**Comment by anton-xqz** [comment]
Hello @i-ky . Your fixe works like a charm. Thanks.
