### ISSUE TITLE
Some text values are not processed - character escaping (?)

### ISSUE THREAD

**Issue by vasekch** [LMacPhail/zabbix-history-influxdb#6]
I have an item of type character in Zabbix. Certain values are not passed to InfluxDB, here is an example of one.

```
Step 11 - click all cases and wait for listing: SCENARIO ERROR line 'page.waitForXPath('//*[@id="EntityListControl"]/div/div/div/div[2]/table/tbody', { timeout: TIMEOUT })': waiting for XPath "//*[@id="EntityListControl"]/div/div/div/div[2]/table/tbody" f
```

I haven't had time for debugging yet, but my best guess is that breaking point may be `@` character. All other special characters (quotes, brackets, ...) I've found in my data elsewhere.

**Comment by i-ky** [comment]
I would blame double quotes. See [this](https://docs.influxdata.com/influxdb/latest/write_protocols/line_protocol_reference/#special-characters).

**Comment by vasekch** [comment]
thanks for that, it may be, but I see other values with quotes sent to InfluxDB without issues

example that works OK:
```
SCENARIO ERROR in step 1 on line 'await page.waitForSelector('a[title="Support"]', { timeout: TIMEOUT });': Navigation Timeout Exceeded: 60000ms exceeded
```

**Comment by vasekch** [comment]
I've replaced `@` in item value for a regular `a` and the problem persist, so my original guess is false.

**Comment by vasekch** [comment]
I've replaced `"` in item value for a `''` (two apostrophes) and it works, so @i-ky was right.

I believe a `"` (quotes) in value coming from `history_string[i].value` needs to be escaped on line https://github.com/LMacPhail/zabbix-history-influxdb/blob/master/src/history_influxdb.c#L392

Similar for `history_text` and `history_log`.

I still can't properly explain why example above works, even when contain `"`, perhaps the fact that it's not next to any ` ` (space).

**Comment by i-ky** [comment]
Here is [line protocol syntax](https://docs.influxdata.com/influxdb/latest/write_protocols/line_protocol_reference/#syntax):
```
<measurement>[,<tag_key>=<tag_value>[,<tag_key>=<tag_value>]] <field_key>=<field_value>[,<field_key>=<field_value>] [<timestamp>]
```
We are talking about `<field_value>`. As we see, it can be followed either by comma (and another `<field_key>=<field_value>` pair) or space and `<timestamp>`.

The only explanation I have is that InfluxDB "swallows" unescaped double quote characters in quoted `<field_value>` if they are not followed by comma or space. In your original problematic value there is a double quote character followed by space
```
..." f
```
Looks like InfluxDB tries to interpret "f" as `<timestamp>` and fails.

**Comment by i-ky** [comment]
@vasekch, if you are interested, you can borrow escaping function from [here](https://github.com/i-ky/effluence/blob/70292fc65414316416a72a85acfaf44cb66ec4af/src/effluence.c#L78-L107). It seems to work:
```
> select * from history_text
name: history_text
time				itemid	value
----				------	-----
2019-02-14T23:40:13.917754293Z	25423	Step 11 - click all cases and wait for listing: SCENARIO ERROR line 'page.waitForXPath('//*[@id="EntityListControl"]/div/div/div/div[2]/table/tbody', { timeout: TIMEOUT })': waiting for XPath "//*[@id="EntityListControl"]/div/div/div/div[2]/table/tbody" f
```

**Comment by vasekch** [comment]
@i-ky thanks for help!
I've implemented quotes escaping into SQL query as is the rest of string manipulation.

**Comment by i-ky** [comment]
My pleasure!
I guess this issue can be closed now.
