### ISSUE TITLE
zabbix db configuration

### ISSUE THREAD

**Issue by anton-xqz** [LMacPhail/zabbix-history-influxdb#8]
Hello,

I would like to know if there is any chance to configure zabbix db different from zabbix_server.conf.
Use case:
As I understand this module takes from zabbix db items and hosts ID and translate them to human readable names. This operation adds some overhead to main database, so I would like to configure this module to work with read replica. This way I will free some resources on busy "write" main db

**Comment by vasekch** [comment]
Good idea.
Unfortunately not, module uses Zabbix internal `DBselect()` which handles whatever is Zabbix server configured for.
This is a trade off of being zabbix module. If this is designed as stand alone service (which we wanted to avoid) it would be possible to reuse SQL queries against different DB. But I'd implement that in something else than pure C ;).
However I believe that overhead to the main DB is small as all the attributes have indexes which should fit to in-memory cache (assuming you don't have millions of hosts/groups/items/applications). 

There is a recent work in the field:
Have a look at https://github.com/i-ky/effluence this doesn't do lookups. You may still get the human readable access to the data in Grafana when used with https://alexanderzobnin.github.io/grafana-zabbix/configuration/direct_db_datasource/#influxdb

But I'm staying with this module to be independent of Zabbix completely, which is my broader concept.

**Comment by vasekch** [comment]
@LMacPhail this is "won't fix", please close.
